### ISSUE TITLE
[deferlow] in facet_server works only with "Scheduler in Overdrive" mode in audio settings

### ISSUE THREAD

**Issue by tomoyanonymous** [mjcella/facet#1]
Hello. Thanks for making this excellent project!
I tried some examples and, at first, it did not work with empty error messages from `dict.unpack`. It seemed like the object failed to refer to dictionaries from specified ids.
Later I noticed that, removing `[deferlow]` object in facet_server.maxpat between `[node.script]` and `[send facet_data]` resolved this error, and also, If I run Max with "Scheduler in Overdrive" mode in audio settings, it worked with `[deferlow]`.

When "Scheduler in Overdrive" is turned off, all event scheduling happens in the main thread, in contrast to an independent thread launches for scheduling in SiO mode, so maybe,  `dict` messages sent to`[deferlow]` object are dropped when not in SiO though I'm not sure.
As long as I tried, `defer` object instead of `deferlow` worked with both modes.

**Comment by nnirror** [comment]
Hey - thanks for reporting this! I will take a look and push a patch for this, hopefully later today.
