### ISSUE TITLE
add several samples to repo

### ISSUE THREAD

**Issue by nnirror** [mjcella/facet#55]
just so they can be referenced in documentation without the user needing to download or move samples into the directory themselves

**Comment by nnirror** [comment]
I'm still considering what samples to add, or if I should simply add a note to the README explaining why no samples are included. (I don't want to influence people's perceptions of what type of music you are supposed to make with Facet by supplying a small handful of samples)

**Comment by glitched01** [comment]
I would say, if you do decide to add samples, add very generic stuff. I'm thinking kicks, snares, etc., some synth stabs and other misc samples. Nothing too crazy. The less a user has to do to get started, the better.

**Comment by nnirror** [comment]
Added 808 samples from freesound.org, originally created November 2001 (!):

https://github.com/mjcella/facet/commit/50f55d448372b0c338e99c3b105470cef11f268a
https://github.com/mjcella/facet/commit/b8f7eaf1c8b1f626f478776d1694f99987fbdbae

Will update the README
