### ISSUE TITLE
percent cpu calculation "cannot read property 'trim' of undefined"

### ISSUE THREAD

**Issue by kindohm** [mjcella/facet#7]
Sometimes the facet server wasn't starting and I tracked it down to an error on this line:

```javascript
let percent_cpu = Number(stdout.split('\n')[1].trim());
```

![image](https://user-images.githubusercontent.com/9797/169650274-dcbf4e18-1e6a-45e9-947b-f7b5ad924efa.png)

While debugging, I found `stdout` to be an empty string. Should probably guard against this.

I got around it by just setting the `percent_cpu` variable to a phony constant string.

Encountered this on Windows 10 and Max 8.2.2.

**Comment by nnirror** [comment]
Great catch, thanks! I don't have a Windows machine to test, but this should safeguard against ever running .trim() on a non-string.

**Comment by nnirror** [comment]
Commit: https://github.com/mjcella/facet/commit/216ddb36ea62b831c46f97a648d0e812dbd60aaf
